# Generated by Django 4.2.4 on 2023-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
