# Generated by Django 4.2.4 on 2023-08-31 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_reservation_is_checked_in_reservation_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='roomimage'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
