# Generated by Django 4.2.4 on 2023-08-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_staff_remove_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_checked_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_checked_out',
        ),
    ]
