# Generated by Django 4.2.4 on 2023-09-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
