# Generated by Django 4.2.4 on 2023-09-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
    ]
