# Generated by Django 4.2.4 on 2023-09-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_room_name_room_r_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_name',
        ),
    ]
