# Generated by Django 4.2.4 on 2023-09-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_room_r_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_name',
        ),
    ]
