# Generated by Django 4.2.4 on 2023-09-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_room_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image',
            new_name='image_file',
        ),
    ]
