# Generated by Django 4.2.4 on 2023-09-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_image_room_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image_file',
            new_name='image',
        ),
    ]
