# Generated by Django 4.2.4 on 2023-09-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_booking_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
