# Generated by Django 4.2.4 on 2023-09-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
    ]
