# Generated by Django 4.2.4 on 2023-09-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
