# Generated by Django 4.2.4 on 2023-09-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_remove_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.booking'),
            preserve_default=False,
        ),
    ]
