# Generated by Django 4.2.4 on 2023-09-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_userinfo_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Booking',
            new_name='booking',
        ),
    ]
