# Generated by Django 4.2.4 on 2023-09-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_remove_userinfo_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.userinfo'),
            preserve_default=False,
        ),
    ]
