# Generated by Django 4.2.4 on 2023-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_booking_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
