# Generated by Django 4.2.4 on 2023-09-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_alter_userinfo_address_alter_userinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userinfo'),
        ),
    ]
