# Generated by Django 4.2.4 on 2023-09-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_alter_feedback_created_at_alter_feedback_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
