# Generated by Django 4.2.4 on 2023-09-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_remove_feedback_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
