# Generated by Django 4.2.4 on 2023-09-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
